import { generateFutureDate } from "./utils";

export const ENDORSEMENT_THRESHOLD = 3;
export const DEFAULT_GROUP_IMAGE = "/pics/1.jpg";

export const SEED_OWNER = {
  id: "seed_admin",
  name: "WizFriends Team",
  tagline: "Curating your starter experiences.",
  homeCity: "Cape Town",
  currentCity: "Cape Town",
  profileCompletion: 100,
  interests: ["Community", "Outdoors", "Food"],
};

export const INITIAL_ACTIVITIES = [
  {
    id: "act-1",
    title: "Sunrise Coastal Run",
    description: "Meet at Mouille Point lighthouse for a 6 km social run. Pace groups for all levels followed by smoothie bowls.",
    category: "Active & Wellness",
    dateTime: generateFutureDate({ daysAhead: 2, hour: 6, minute: 30 }),
    location: "Mouille Point Lighthouse",
    city: "Cape Town",
    host: "WizFriends Team",
    hostId: SEED_OWNER.id,
    distance: 3,
    attendees: 18,
    tags: ["running", "wellness", "outdoors"],
    isNearby: true,
    featured: false,
    isVirtual: false,
  },
  {
    id: "act-2",
    title: "Neighbourhood Potluck Picnic",
    description: "Bring a dish from home and meet other expats at Green Point Park. Family-friendly with lawn games.",
    category: "Social & Connection",
    dateTime: generateFutureDate({ daysAhead: 4, hour: 12, minute: 0 }),
    location: "Green Point Urban Park",
    city: "Cape Town",
    host: "WizFriends Team",
    hostId: SEED_OWNER.id,
    distance: 5,
    attendees: 42,
    tags: ["food", "family", "outdoors"],
    isNearby: true,
    featured: true,
    isVirtual: false,
  },
  {
    id: "act-3",
    title: "Remote First Coffee Crawl",
    description: "Explore three remote worker-friendly cafes in the CBD with co-working tasters and latte art throwdowns.",
    category: "Professional & Networking",
    dateTime: generateFutureDate({ daysAhead: 5, hour: 9, minute: 0 }),
    location: "Cape Town CBD",
    city: "Cape Town",
    host: "Remote Collective",
    hostId: SEED_OWNER.id,
    distance: 6,
    attendees: 27,
    tags: ["cowork", "coffee", "networking"],
    isNearby: true,
    featured: true,
    isVirtual: false,
  },
  {
    id: "act-4",
    title: "Virtual UX Crit Club",
    description: "Designers from around the world rotate sharing projects for feedback in a 60-minute lightning format.",
    category: "Tech & Learning",
    dateTime: generateFutureDate({ daysAhead: 3, hour: 18, minute: 0 }),
    location: "Online",
    city: "Remote",
    host: "UX Collective",
    hostId: SEED_OWNER.id,
    distance: 0,
    attendees: 65,
    tags: ["design", "virtual", "learning"],
    isNearby: false,
    featured: false,
    isVirtual: true,
  },
  {
    id: "act-5",
    title: "Sunset Film Club: Outdoor Screening",
    description: "Watch a cult-classic under the stars with silent-disco headsets. Popcorn and hot drinks included.",
    category: "Arts & Culture",
    dateTime: generateFutureDate({ daysAhead: 6, hour: 19, minute: 0 }),
    location: "Battery Park Amphitheatre",
    city: "Cape Town",
    host: "WizFriends Film Club",
    hostId: SEED_OWNER.id,
    distance: 4,
    attendees: 54,
    tags: ["film", "outdoors", "social"],
    isNearby: true,
    featured: false,
    isVirtual: false,
  },
  {
    id: "act-6",
    title: "African Fusion Supper Club",
    description: "Monthly dinner party featuring a chef's tasting menu and storytelling from local creatives.",
    category: "Food & Drink",
    dateTime: generateFutureDate({ daysAhead: 8, hour: 20, minute: 0 }),
    location: "Woodstock Exchange Loft",
    city: "Cape Town",
    host: "WizFriends Team",
    hostId: SEED_OWNER.id,
    distance: 8,
    attendees: 32,
    tags: ["food", "culture", "networking"],
    isNearby: true,
    featured: false,
    isVirtual: false,
  },
  {
    id: "act-7",
    title: "Tabletop Thursday",
    description: "Board games, RPGs, and strategy classics. Bring a snack and meet fellow gamers.",
    category: "Social & Connection",
    dateTime: generateFutureDate({ daysAhead: 1, hour: 18, minute: 30 }),
    location: "Obs Community Hub",
    city: "Cape Town",
    host: "WizFriends Game Guild",
    hostId: SEED_OWNER.id,
    distance: 7,
    attendees: 21,
    tags: ["games", "indoors", "social"],
    isNearby: true,
    featured: false,
    isVirtual: false,
  },
  {
    id: "act-8",
    title: "Impact Lab Volunteering",
    description: "Join monthly impact sprints supporting local NGOs with marketing, funding, and operations.",
    category: "Social Impact",
    dateTime: generateFutureDate({ daysAhead: 10, hour: 10, minute: 30 }),
    location: "Workshop17 Waterfront",
    city: "Cape Town",
    host: "Impact Lab Collective",
    hostId: SEED_OWNER.id,
    distance: 5,
    attendees: 16,
    tags: ["volunteer", "skills", "community"],
    isNearby: true,
    featured: false,
    isVirtual: false,
  },
];

export const INITIAL_GROUPS = [
  {
    id: "group-1",
    name: "Weekend Trail Runners",
    description: "Saturday sunrise trail missions focused on inclusive pacing and post-run coffee rituals.",
    baseLocation: "Signal Hill",
    nextActivity: "Sat · 06:00 · Lion's Head loop",
    cadence: "Weekly",
    tags: ["running", "outdoors", "wellness"],
    isPrivate: false,
    isPublic: true,
    image: "/pics/7.jpg",
    photographer: null,
    photographerUrl: null,
    membersCount: 68,
    ownerId: SEED_OWNER.id,
    adminIds: [SEED_OWNER.id],
    memberIds: [SEED_OWNER.id],
  },
  {
    id: "group-2",
    name: "Film & Feast Society",
    description: "A community of cinephiles hosting themed screenings paired with curated menus.",
    baseLocation: "Gardens",
    nextActivity: "Fri · 19:30 · Documentary night",
    cadence: "Bi-weekly",
    tags: ["film", "food", "storytelling"],
    isPrivate: false,
    isPublic: true,
    image: "/pics/5.jpg",
    photographer: null,
    photographerUrl: null,
    membersCount: 42,
    ownerId: SEED_OWNER.id,
    adminIds: [SEED_OWNER.id],
    memberIds: [SEED_OWNER.id],
  },
  {
    id: "group-3",
    name: "Global Remote Workers Circle",
    description: "Daily accountability check-ins, pop-up co-working, and networking with nomads.",
    baseLocation: "Hybrid",
    nextActivity: "Thu · 09:00 · Waterfront cowork",
    cadence: "Multi-week",
    tags: ["cowork", "professional", "remote"],
    isPrivate: true,
    isPublic: false,
    image: "/pics/2.jpg",
    photographer: null,
    photographerUrl: null,
    membersCount: 105,
    ownerId: SEED_OWNER.id,
    adminIds: [SEED_OWNER.id],
    memberIds: [SEED_OWNER.id],
  },
  {
    id: "group-4",
    name: "Mindful Makers",
    description: "Creative workshops blending art therapy, ceramics, and journaling for mindful living.",
    baseLocation: "Observatory",
    nextActivity: "Sun · 15:00 · Clay & conversation",
    cadence: "Monthly",
    tags: ["creativity", "wellness", "mindfulness"],
    isPrivate: false,
    isPublic: true,
    image: "/pics/6.jpg",
    photographer: null,
    photographerUrl: null,
    membersCount: 53,
    ownerId: SEED_OWNER.id,
    adminIds: [SEED_OWNER.id],
    memberIds: [SEED_OWNER.id],
  },
];

export const INITIAL_IDEAS = [
  {
    id: "idea-1",
    title: "Sunset Language Exchange on Signal Hill",
    description: "Pair up with locals for rotating 15-minute language exchanges followed by shared snacks.",
    category: "Arts & Culture",
    tags: ["language", "sunset", "culture"],
    supporters: ["Naledi", "Zahi"],
    suggestedTime: "Friday 18:00",
    preferredLocation: "Signal Hill lookout",
    status: "open",
    createdById: SEED_OWNER.id,
  },
  {
    id: "idea-2",
    title: "Community Impact Hack Night",
    description: "Collaborate on civic tech problems pitched by NGOs and present prototypes by the end of the night.",
    category: "Tech & Learning",
    tags: ["civic-tech", "volunteer", "innovation"],
    supporters: ["Ivy", "Ruben", "Noor"],
    suggestedTime: "Wednesday 17:30",
    preferredLocation: "Workshop17 Waterfront",
    status: "ready",
    createdById: SEED_OWNER.id,
  },
  {
    id: "idea-3",
    title: "Cape Town Kayak Buddies",
    description: "Match with paddle partners for bi-weekly sea kayaking adventures with rotating routes.",
    category: "Active & Wellness",
    tags: ["kayak", "ocean", "fitness"],
    supporters: [],
    suggestedTime: "Saturday 07:00",
    preferredLocation: "Three Anchor Bay Slipway",
    status: "open",
    createdById: SEED_OWNER.id,
  },
];

export const INITIAL_NOTIFICATIONS = [];

export function buildDefaultProfile(user) {
  const baseName =
    user?.displayName ||
    (user?.email ? user.email.split("@")[0] : null) ||
    "Community Member";

  return {
    name: baseName,
    email: user?.email || "",
    tagline: "Let's build community together.",
    homeCity: "",
    currentCity: "Cape Town",
    profileCompletion: 35,
    interests: [],
    favourites: [],
    joinedActivities: [],
    savedActivities: [],
    joinedGroups: [],
    photoURL: user?.photoURL || "",
    role: "user",
  };
}
