export function generateFutureDate({ daysAhead, hour, minute }) {
  const date = new Date();
  date.setDate(date.getDate() + daysAhead);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export function buildDateFromForm(date, time) {
  if (date && time) {
    const combined = new Date(`${date}T${time}`);
    if (!Number.isNaN(combined.getTime())) {
      return combined.toISOString();
    }
  }
  const fallback = new Date();
  fallback.setDate(fallback.getDate() + 5);
  fallback.setHours(18, 0, 0, 0);
  return fallback.toISOString();
}

const CATEGORY_KEYWORDS = [
  { slug: "food", category: "Food & Drink", keywords: ["food", "chef", "cook", "dinner", "brunch", "coffee", "restaurant"] },
  { slug: "active", category: "Active & Wellness", keywords: ["run", "hike", "yoga", "workout", "fitness", "climb", "kayak", "surf"] },
  { slug: "culture", category: "Arts & Culture", keywords: ["film", "movie", "gallery", "art", "music", "museum", "poetry"] },
  { slug: "learning", category: "Tech & Learning", keywords: ["tech", "code", "startup", "design", "ux", "ai", "learning", "workshop"] },
  { slug: "impact", category: "Social Impact", keywords: ["volunteer", "impact", "ngo", "charity", "community service", "donate"] },
];

const IDEA_BLUEPRINTS = {
  social: [
    { title: "Community Connections Mixer", tags: ["social", "welcome"] },
    { title: "Story Swap & Snacks", tags: ["stories", "food"] },
  ],
  food: [
    { title: "City Flavours Progressive Dinner", tags: ["food", "culture"] },
    { title: "Street Food Taste Tour", tags: ["street-food", "explore"] },
  ],
  active: [
    { title: "Sunrise Movement Club", tags: ["fitness", "outdoors"] },
    { title: "Adventure Buddy Match-up", tags: ["outdoors", "community"] },
  ],
  culture: [
    { title: "Art House Pop-up Night", tags: ["arts", "film"] },
    { title: "Creative Collab Lab", tags: ["creative", "collab"] },
  ],
  learning: [
    { title: "Curious Minds Salon", tags: ["learning", "discussion"] },
    { title: "Hands-on Maker Studio", tags: ["maker", "skills"] },
  ],
  impact: [
    { title: "Do-Good Sprint Session", tags: ["impact", "volunteer"] },
    { title: "Community Project Power Hour", tags: ["community", "action"] },
  ],
};

const TIME_SLOTS = [
  "Thursday 18:30",
  "Friday 19:00",
  "Saturday 10:00",
  "Saturday 16:00",
  "Sunday 11:00",
  "Wednesday 17:30",
];

const LOCATION_LIBRARY = {
  social: ["Rooftop lounge in {city}", "Community co-working terrace", "Seaside promenade picnic spot"],
  food: ["Hidden supper club loft in {city}", "Chef's studio kitchen", "Local food market pavilion"],
  active: ["Green Point Urban Park", "Sea Point Promenade", "Lion's Head base camp"],
  culture: ["Independent cinema courtyard", "Local art gallery studio", "Cultural hub in {city}"],
  learning: ["Innovation lab at Workshop17", "Makerspace in Woodstock", "Downtown co-creation loft"],
  impact: ["Neighbourhood community centre", "Partnership hub at Waterfront", "NGO accelerator space"],
};

export function generateIdeaFromPrompt(prompt, currentCity) {
  const lower = prompt.toLowerCase();
  const matchedCategory =
    CATEGORY_KEYWORDS.find((entry) =>
      entry.keywords.some((keyword) => lower.includes(keyword))
    ) || { slug: "social", category: "Social & Connection" };

  const blueprints = IDEA_BLUEPRINTS[matchedCategory.slug] || IDEA_BLUEPRINTS.social;
  const blueprint = blueprints[Math.floor(Math.random() * blueprints.length)];

  const locationOptions = LOCATION_LIBRARY[matchedCategory.slug] || LOCATION_LIBRARY.social;
  const preferredLocation = locationOptions[Math.floor(Math.random() * locationOptions.length)].replace("{city}", currentCity);

  const suggestedTime = TIME_SLOTS[Math.floor(Math.random() * TIME_SLOTS.length)];

  const formattedPrompt =
    prompt.charAt(0).toUpperCase() + prompt.slice(1).replace(/\.$/, "");

  return {
    title: blueprint.title,
    description: `${formattedPrompt}. Meet new people and test a fresh idea generated by the community.`,
    category: matchedCategory.category,
    tags: blueprint.tags,
    preferredLocation,
    suggestedTime,
  };
}

const DAY_INDEX = {
  Sunday: 0,
  Monday: 1,
  Tuesday: 2,
  Wednesday: 3,
  Thursday: 4,
  Friday: 5,
  Saturday: 6,
};

export function createDateFromSuggestion(suggestion) {
  const match = suggestion.match(
    /(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday)\s+(\d{1,2}):(\d{2})/i
  );
  const now = new Date();
  if (!match) {
    const fallback = new Date(now);
    fallback.setDate(now.getDate() + 3);
    fallback.setHours(18, 0, 0, 0);
    return fallback.toISOString();
  }

  const [, dayNameRaw, hourRaw, minuteRaw] = match;
  const dayName =
    dayNameRaw.charAt(0).toUpperCase() + dayNameRaw.slice(1).toLowerCase();
  const targetDay = DAY_INDEX[dayName];
  const hour = Number(hourRaw);
  const minute = Number(minuteRaw);

  const eventDate = new Date(now);
  const diff = (targetDay + 7 - now.getDay()) % 7 || 7;
  eventDate.setDate(now.getDate() + diff);
  eventDate.setHours(hour, minute, 0, 0);
  return eventDate.toISOString();
}

